name: parcel-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - hdf5
  - cmake
  - compilers
  - openpmd-beamphysics
  - pre-commit
  - pip
  - pip:
    - git+https://github.com/openPMD/openPMD-validator@2.0.X